// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tdAPI.Data;

#nullable disable

namespace tdAPI.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    partial class ToDoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("tdAPI.Models.ToDo", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("ToDoId");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            ToDoId = 1,
                            CreatedTime = new DateTime(2022, 12, 7, 17, 43, 37, 836, DateTimeKind.Utc).AddTicks(7070),
                            DueBy = new DateTime(2022, 12, 7, 17, 43, 37, 836, DateTimeKind.Utc).AddTicks(7070),
                            Importance = 1,
                            Title = "First todo"
                        },
                        new
                        {
                            ToDoId = 2,
                            CreatedTime = new DateTime(2022, 12, 7, 17, 43, 37, 836, DateTimeKind.Utc).AddTicks(7070),
                            DueBy = new DateTime(2022, 12, 7, 17, 43, 37, 836, DateTimeKind.Utc).AddTicks(7070),
                            Importance = 9,
                            Title = "Second todo"
                        });
                });

            modelBuilder.Entity("tdAPI.Models.ToDoList", b =>
                {
                    b.Property<int?>("ToDoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ToDoListId");

                    b.ToTable("ToDoLists");

                    b.HasData(
                        new
                        {
                            ToDoListId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
